# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(help_text='(max) 12 Character version number e.g. 1.0.1 or in progress', max_length=12, verbose_name='Version'),
        ),
    ]
