# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0003_auto_20170217_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howdy.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
